### ISSUE TITLE
How do I integrate your editor into my web application?

### ISSUE THREAD

**Issue by rstemmer** [liyasthomas/marcdown#1]
**Is your feature request related to a problem? Please describe.**
I'd like to use your marcdown-editor in one of my projects, but I have no idea how it is supposed to be used inside other projects.

**Describe the solution you'd like**
A documentation explaining how to use your editor inside other projects would help a lot.
Some kind of installation-manual would be nice.
Furthermore a short description on how to modify the code would be nice as well.

**Describe alternatives you've considered**
There is no alternative to a documentation ;)
Having some kind of build or deploy directory containing ready-to-use files that just needs to be included in the main HTML file will also work as long as the project is as small as this project is.

**Additional context**
I was just looking at the code to figure out if simple copy&paste would be enough to use your editor. Obviously it is not, because index.css defindes properties of body and other basic HTML elements. So using this file directly would break the whole application :)

**Comment by liyasthomas** [comment]
How do I integrate your editor into my web application?
> You'll have to wait couple of days until I release Marcdown Library ✨

Regarding documentation:
> Marcdown is built with primarily two libraries:
> 1. **[MarkedJS](https://marked.js.org)** - For markdown parser
> 2. **[highlightjs](https://highlightjs.org)** - For code highlighting
> along with some help of HTML, CSS and JavaScript.

Regarding Marcdown Library (WIP) 🚀
> Currently Marcdown is a standalone progressive web application to create, edit, view and save Markdown files. To use this in your own web application you can either build a similar application using **[MarkedJS](https://marked.js.org)** and **[highlightjs](https://highlightjs.org)** or wait for Markdown library release. Library will be a single JavaScript file which you can import on any web application to make similar editor and preview screen 🎉👌

**Comment by liyasthomas** [comment]
# Introducing Marcdown Library (alpha) ⚗
Refer here for installation: https://github.com/liyasthomas/marcdown#installing

Refer here for sample file: https://github.com/liyasthomas/marcdown#example-html-file

More updates coming soon ✨
