### ISSUE TITLE
Markdown & Text is not visbile in day/light mode

### ISSUE THREAD

**Issue by iamabs2001** [liyasthomas/marcdown#10]
**Describe the bug**
The Input and output text is not visible in light mode app.

**To Reproduce**
1. Go to liyasthomas.github.io/marcdown
2. type something in input
3. the input color is not properly visbile.
![Screenshot at 2020-05-31 06-36-00](https://user-images.githubusercontent.com/48883819/83346020-acbf4880-a336-11ea-933e-5236216aa023.png)

**Expected behavior**
Should be visible

**Desktop (please complete the following information):**
 - OS: Parrot 4.6 64-bit
 - Browser: Chrome 
 - Version: 75.0.3770.100 (Official Build) (64-bit)

**Additional context**
Theme Should follow Proper Contrast Ration of font color and background color.

**Comment by liyasthomas** [comment]
Are you using any 3rd party themes? Seems like an extension/theme has been overriding Marcdown default theme. Disable such apps and try again.

Issue is non-replicatable at my end.
