### ISSUE TITLE
Inline code block move to new line

### ISSUE THREAD

**Issue by mittalyashu** [liyasthomas/marcdown#2]
**Describe the bug**

Adding an inline code block using black ticks ` moves the code to a new line.

![image](https://user-images.githubusercontent.com/29014463/60507921-e632a280-9ce6-11e9-8fe0-ef0c7ef6b266.png)

**Comment by liyasthomas** [comment]
Issue has be identified. Thanks for the concern. Issue will be fixed in the next commit.

**Comment by liyasthomas** [comment]
🐛 Fixed inline code block appending new line to preview.
Kindly test some use cases and share feedback.

By the way, what's new on Marcdown?
✨ Added MathJax support for LaTeX, MathML, and AsciiMath notations. Hooray..! 🎉
