### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by arjvik** [liyasthomas/marcdown#4]
First of all, I want to thank you for writing this amazing markdown editor! It not only looks beautiful, but seems to do its job well too!

The feature I would like to see implemented is MathJax support. This would allow us to write mathematical equations in plain text, using LaTeX syntax, and have them rendered beautifully as images behind the scenes using the MathJax library.

**Describe the solution you'd like**
I propose that there are two types of equations, inline and block, just like inline code (<code>\` ... \` </code>) and code blocks (<code>\`\`\` ...... \`\`\`</code>).

Inline equations are delimited on both sides by single `$` symbols as such: `The boy wrote $1+1=2$ on the board`. A backslash is used to escape `$` symbols in the equation (this is usually handled by MathJax itself.

Block equations are seperated by blank lines (just like paragraphs), and have lines containing only `$$` above and below. Here is an example:

```markdown
Einstein's most famous equation is:

$$
E = m \cdot c^2
$$

He is also known for his Theory of General Relativity.
```

**Reference syntax and rendering**
Here is a reference markdown file using one block and one inline equation:  
[MathJax.md](https://github.com/liyasthomas/marcdown/files/3351971/MathJax.md.txt)

Here is how it should look when rendered (this was done via [Typora](typora.io), an editor similar to this but closed-source.):  
[MathJax.pdf](https://github.com/liyasthomas/marcdown/files/3351975/MathJax.pdf)

**Additional comments**
As I mentioned earlier, Typora does this and was the inspiration for the syntax used here. I love Typora, except for the fact that it is closed-source and will become commercial when its beta period is over. I think that you should look into Typora for inspiration, as many of its features, like MathJax, Inline WYSIWYG, diagrams, tables, custom CSS themes, and such are quite useful.

Anyway, thanks for such an amazing editor!

**Comment by liyasthomas** [comment]
Issue has been identified. Will add MathJax support in next commit ✨

**Comment by liyasthomas** [comment]
✨ Added MathJax support for LaTeX, MathML, and AsciiMath notations. Hooray..! 🎉

Kindly test some use cases and share feedback ❤️

**Comment by arjvik** [comment]
It seemed to work when I quickly played aroud with it!

Looks great!
