### ISSUE TITLE
Letters not showing on preview side occasionally

### ISSUE THREAD

**Issue by TheFern2** [liyasthomas/marcdown#6]
**Describe the bug**
Sometimes words do not show complete on the preview window. It is happening randomly.

**To Reproduce**
1. Type a document on the markdown side
2. Watch the preview, missing a few letters
3. After manually scrolling or clicking around letters appear

**Expected behavior**
I believe words should show entirely as you types

**Desktop (please complete the following information):**
 - Mac Mojave
 - Chrome
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Additional context**

![Screen Shot 2019-07-03 at 11 13 49 PM](https://user-images.githubusercontent.com/10265682/60639455-64c33900-9de8-11e9-91d5-2a4c40422bd3.png)

**Comment by liyasthomas** [comment]
Removed delay between editor and viewer. Probably fixed now.
