### ISSUE TITLE
Scroll lock for markdown/preview

### ISSUE THREAD

**Issue by TheFern2** [liyasthomas/marcdown#7]
**Is your feature request related to a problem? Please describe.**
The issue is that the preview window does not scroll as you are typing down.

**Steps to see issue.**
1. Type paragraphs until markdown window is full
2. the preview starts to jump up and down as you type.
3. Scroll markdown window down
4. Type some more
5. Markdown window jumps back to the top

**Describe the solution you'd like**
Preview should be automatically scrolling as you are typing or scrolling markdown side.

**Comment by liyasthomas** [comment]
@kodaman2 Synchronized scroll feature is in beta and will be stable in couple of days ✨

**Comment by liyasthomas** [comment]
# Thank you for the donation ❤
_This means so much to me.
Thank you for the appreciation._

I made your issues and feature requests my top priority.
Added scroll sync feature. Fixed scroll bug.
More features coming on the way!

**Comment by TheFern2** [comment]
> # Thank you for the donation ❤
> _This means so much to me. Thank you for the appreciation._
> 
> I made your issues and feature requests my top priority.
> Added scroll sync feature. Fixed scroll bug.
> More features coming on the way!

It is an awesome project I had to show some love. Oh wow thanks for the fast turn around!
